### ISSUE TITLE
simplenote app and website

### ISSUE THREAD

**Issue by hermeneut** [AdguardTeam/HttpsExclusions#394] opened 2021-04-10 21:43 UTC
i just bought adguard lifetime licence, but i can't use Simplenote app and their website https://app.simplenote.com. i'm sure that adguard somehow block it, because it works fine on my android phone with wireless off.

please, can you tell me how to fix it?

hermeneut@live.com

**Comment by Chinaski1** [comment] 2021-08-09 12:57
@hermeneut 

Hello there!
Sorry for so late reply.
I try to reproduce your issue and doesn't account for any issues with the website or specified application.
Could you check and let us know the result?

**Comment by Chinaski1** [comment] 2021-08-23 08:46
I close this task due to not reply

**Closed by Chinaski1** 2021-08-23 08:46 UTC
