### ISSUE TITLE
Samsung browser

### ISSUE THREAD

**Issue by joedownloads1** [AdguardTeam/HttpsExclusions#409] opened 2021-07-25 14:04 UTC
Samsung browser does not sync data to samsung cloud (sync failed) only when https filtering is enabled. 
I have of course installed certificate onto android device.

**Comment by Chinaski1** [comment] 2021-07-26 09:48
Hello @joedownloads1 

I can't reproduce the specified issues on my side.
There are no failures with Samsung cloud synchronization.

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
4. Specify the Samsung Browser version
3. Send received archive to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Chinaski1** [comment] 2021-07-29 11:14
And could you check what certificate is shown in the browser if you click on the icon "lock" next to the input field of the domain?

**Comment by joedownloads1** [comment] 2021-08-01 14:54
I have sent an image of the certificate

-------- Original Message --------

**Comment by joedownloads1** [comment] 2021-08-02 11:48
have sent an image of the certificate
![Screenshot_20210801-164615_Samsung_Internet_Beta](https://user-images.githubusercontent.com/50712798/127857251-de8aa725-753e-4a0c-8e05-4ea14498f1dd.jpg)

**Comment by Chinaski1** [comment] 2021-08-06 08:49
@joedownloads1 
I think the best solution would be to add exclusion rules.

Open AdGuard settings -> Content Blocking -> User rules -> add these rules:

- @@||api.samsungcloud.com^$app=com.sec.android.app.sbrowser - for Release version
- @@||api.samsungcloud.com^$app=com.sec.android.app.sbrowser.beta  - for Beta version

**Comment by joedownloads1** [comment] 2021-08-06 12:41
I did as you suggested but it did not work.
I must say the samsung sync works for all other apps except samsung browser. Sync works for browser also if i disable https filtering for samsung browser and leave all other blocking for browser on.
And the browser sync does not work if i disable everything except https filtering so it must be something to do with the https filteting.

-------- Original Message --------

**Comment by Chinaski1** [comment] 2021-08-06 13:04
You can also add the specified domain to the HTTPS exceptions list

- AdGuard -> Setitings ->  Network -> HTTPS filtering -> Allowlist

**Comment by joedownloads1** [comment] 2021-08-06 13:09
I have added exepctions but ut still wont sync. Its weird because i see no traffic in log after i try to sync

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Chinaski1** [comment] 2021-08-06 14:38
Pretty weird behavior 

Can you collect the log files one more time with allowlisted domain?

**Comment by joedownloads1** [comment] 2021-08-06 15:13
I have sent logs through email. What about the samsung browser addon. The addon doesnt https filter right? Coz if it does i could just pass samsung browser and use addon. 
So you saied "I can't reproduce the specified issues on my side." Did you try and sync in browser and it synced? Coz i have a screen shot that looks like this:
![Screenshot_20210806-171306_Samsung Internet Beta](https://user-images.githubusercontent.com/50712798/128532509-3192d88a-b286-4292-9416-c05347eb3bbb.jpg)

**Comment by joedownloads1** [comment] 2021-08-06 15:15
Logs are in attachment

-------- Original Message --------

**Comment by Chinaski1** [comment] 2021-08-09 11:01
Sorry but I can't find your email with logs, can you send it one more time?
Yes, I can [synchronize](https://uploads.adguard.com/Chinaskin0yh2.png) in both the regular and beta versions of the Samsung browser.

**Comment by joedownloads1** [comment] 2021-08-09 11:50
Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Chinaski1** [comment] 2021-08-09 15:35
Are you sending the report to devteam@adguard.com?

**Comment by joedownloads1** [comment] 2021-08-09 18:06
I have just sent it to devteam

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by joedownloads1** [comment] 2021-08-09 18:53
I realized that only beta doesnt sync so i went to none beta version and it works now. I hope it wont stop working after the 15. Version update. Thanks for the help

**Comment by Chinaski1** [comment] 2021-08-10 08:37
Glad to hear it!

So I close this task. Reopen it if the issues recourse.

**Closed by Chinaski1** 2021-08-10 08:37 UTC
